### ISSUE TITLE
Growth_rate

### ISSUE THREAD

**Issue by DarkAlchy** [konstmish/prodigy#15]
Would you be so kind as to direct me to a place that describes what this does and what to set it at?  I have seen it set to Infinity , or 1, or 1.02 before, and I have tested it at 10, but I don't know what it does.

**Comment by DanPli** [comment]
growth_rate (float):
            "prevent the D estimate from growing faster than this multiplicative rate.
            Default is inf, for unrestricted. Values like 1.02 give a kind of learning
            rate warmup effect."

**Comment by DarkAlchy** [comment]
Thank you.
