### ISSUE TITLE
Lowering TE or Unet average only

### ISSUE THREAD

**Issue by trihardseven** [konstmish/prodigy#16]
Using Prodigy to train SDXL loras specifically, is it possible to force a smaller learning rate for the TE or UNET only? Something like adjusting the d_coef, but only for one of them.

**Comment by adefazio** [comment]
Please try out the version in this pull request, it supports different LR values for different layers via setting the layer_scale for each in the param group: 
https://github.com/konstmish/prodigy/pull/9

**Comment by konstmish** [comment]
Closing this as the original question was answered.
