### ISSUE TITLE
Is the any rule of the thumb for tuning weight_decay of Prodigy when training transformers-based LLMs?

### ISSUE THREAD

**Issue by DesperateExplorer** [konstmish/prodigy#5]
Dear authors:

Given a well tuned `AdamW` for a transformers-based LLM, to compare the performance of `AdamW` with `Prodigy(AdamW)` for training such a model, is there any rule of the thumb for tuning `weight_decay` of `Prodigy(AdamW)`, i.e., is there any suggestion on the linear scaling of `weight_decay` when transferring the hyper-parameters from this vanilla `AdamW` to `Prodigy(AdamW)`?

**Comment by konstmish** [comment]
Thanks for reaching out! If you use `Prodigy` with `decouple=True` (the default value), it should be very similar to `AdamW`. In our experiments, we used the same values for both methods, typically `0.1` or `0.05`.

Did you do any preliminary experiments that prompted the question?

**Comment by adefazio** [comment]
I wound chime in that sometimes it helps to try a value double the usual value you would use, particularly in cases where prodigy is choosing a larger step-size than people typically use on the problem. I wouldn't bother sweeping over other values besides those two options.

**Comment by konstmish** [comment]
Closing the issue as the question seems to have been answered.
